### ISSUE TITLE
Task #1 feedback

### ISSUE THREAD

**Issue by marielledado** [laufergall/webscraping_workshop#7]
I managed to do Task 1 in around 10 minutes (not counting finding my way around Windows command line hahah that took about another 10 minutes). It's a good task to start the workshop with!

I have a few suggestions:

1. Clone or download main project
- instead of `<project-dir>` maybe you can directly write `movies-knowledgegraph-workshop`, since when you download the zip file `movies-knowledgegraph-workshop` is the default directory name anyway?

2. Install scrapy project requirements
- My OS is Windows and I used the Anaconda Prompt to do this step. For some reason, it would only work when I used a backward slash `cd <project-dir>\scrapy` instead of forward slash `cd <project-dir>/scrapy`.

3. Scrape data and write to JSON file
- Could you maybe mention the directory in which the scraped data is stored? Maybe add in the instructions: "The scraped data is stored in a JSON file under `\scrapy\data\kinoprogramm.json`" Of course you can infer this info from the commands you enter, but it's good to mention it again so that it's easy to find.

Thanks!

**Comment by laufergall** [comment]
Changes added in [commit](https://github.com/laufergall/webscraping_workshop/commit/46c1f9647b610daa787fbe7e4dea92998dd8aefe). Thanks!
