### ISSUE TITLE
Task #2 Feedback

### ISSUE THREAD

**Issue by marielledado** [laufergall/webscraping_workshop#8]
This was of course a bit more challenging but very fulfilling when you finally get it right!!

1. Prepare docker
- I did this step the other day with no issues other than using Linux containers instead of Windows containers

2. Add docker-compose.yml

- since there is no "Download" button in the .yml link, you might want to say something like "copy and paste these lines and save as .yml file" or something (I initially right-clicked > save but that saved even the html/css of the link)
- Just like in Task 1, you might want to refer to `<project-dir>` as `movies-knowledgegraph-workshop`. There is no `.gitignore` file since I just downloaded the files in a zip file (and didn't create a repo).

3. Adapt scrapy pipeline
- There is already something written in `Line 72` but it is commented out. Should we delete/replace these commented lines or do we simply leave them alone and just insert `ITEM_PIPELINES`?

4. Start the three containers
- This step was rather confusing to me. I did what was written in the instructions and ran the following lines once:
```
cd <project-dir>
docker-compose build
docker-compose up
```
As I told you then, only this container was up:
```
(base) C:\Users\Marielle Dado>docker ps
CONTAINER ID        IMAGE                                    COMMAND                  CREATED             STATUS              PORTS                      NAMES
7f332c2b31dc        movies-knowledgegraph-workshop_mongodb   "docker-entrypoint.s…"   2 hours ago         Up 7 minutes        0.0.0.0:27017->27017/tcp   mongodb
```
Then you advised me to do `docker-compose down`, then `docker-compose build `, and then `docker-compose up`, then it finally worked--i saw `mongodb` and `mongoclient` containers up. Should you maybe include these instructions too?

5. Connect to db from Mongoclient
As already discussed, `mongodb` should in some cases be used as host. Using Robo3T instead of NoSQLclient helped solve the issue.

Also, you might want to check the anchoring/referencing of some sections of the instructions. Like e.g., [before](# Prepare docker) didn't quite appear as a link

Will continue with Task 3 tomorrow!

**Comment by laufergall** [comment]
Changes added in [this commit](https://github.com/laufergall/webscraping_workshop/commit/46c1f9647b610daa787fbe7e4dea92998dd8aefe). Thanks!
