### ISSUE TITLE
Task #3 Feedback

### ISSUE THREAD

**Issue by marielledado** [laufergall/webscraping_workshop#9]
Task #3 is done! Was pretty straightforward and cool to see everything come together! I think it's going to be a great workshop :) 🥇 

Just a few comments to make the instructions clearer:

1. Add backend service to docker-compose.yml
- how can the participants tell that the container is done building? Maybe write what code to expect (is it `mongodb        | 2020-03-28T19:58:41.065+0000 I  ACCESS   [conn488] Successfully authenticated as principal root on kinoprogramm from client 172.19.0.4:47140`?)

2. Access the API endpoints
- Please mention how to "Call the GET endpoint" (i.e., by clicking the button, etc)
- Also mention that it might take a few minutes til `http://<local host>:8001/movies/titles
` works, for people who may be impatient and think it's not working (like me haha)

Thank you SO MUCH for creating this wonderful workshop!!

**Comment by laufergall** [comment]
Changes added in [this commit](https://github.com/laufergall/webscraping_workshop/commit/46c1f9647b610daa787fbe7e4dea92998dd8aefe). I'm glad you liked the workshop, thanks a lot for all your feedback.
